import "~/styles/globals.css";

import { Inter } from "next/font/google";
import Navbar from "../Navbar";
import Sidebar from "../../components/Sidebar";
import { Suspense } from "react";
import Loading from "./loading";
import { validateRequest } from "~/auth";
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Biodata",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { user } = await validateRequest();
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable} `}>
        <Sidebar user={user} />
        <main className="grid h-full w-full  pl-[300px]">
          <Navbar />
          <div className="flex h-full w-full items-center justify-center  p-4">
            <Suspense fallback={<Loading />}>{children}</Suspense>
          </div>
        </main>
      </body>
    </html>
  );
}
